# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jumpstart}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["i0n"]
  s.date = %q{2010-05-24}
  s.default_executable = %q{jumpstart}
  s.description = %q{JumpStart is a script runner and template parser written in Ruby with Ruby projects in mind.

                        That said it should function equally well for any project in any language where many actions need to be performed to setup a new project.
}
  s.email = %q{ianalexanderwood@gmail.com}
  s.executables = ["jumpstart"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".bundle/config",
     ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/jumpstart",
     "config/jumpstart_setup.yml",
     "jumpstart.gemspec",
     "jumpstart_templates/i0n_rails_3/.gitignore",
     "jumpstart_templates/i0n_rails_3/_._Gemfile",
     "jumpstart_templates/i0n_rails_3/app/views/home/index.haml",
     "jumpstart_templates/i0n_rails_3/app/views/layouts/application.haml",
     "jumpstart_templates/i0n_rails_3/config/_2._routes.rb",
     "jumpstart_templates/i0n_rails_3/config/_L._database.yml",
     "jumpstart_templates/i0n_rails_3/config/deploy.rb",
     "jumpstart_templates/i0n_rails_3/config/environments/_18._development.rb",
     "jumpstart_templates/i0n_rails_3/config/environments/_27._test.rb",
     "jumpstart_templates/i0n_rails_3/config/environments/_41._production.rb",
     "jumpstart_templates/i0n_rails_3/config/initializers/setup_mail.rb",
     "jumpstart_templates/i0n_rails_3/jumpstart_config/i0n_rails_3.yml",
     "jumpstart_templates/i0n_rails_3/jumpstart_config/nginx.local.conf",
     "jumpstart_templates/i0n_rails_3/jumpstart_config/nginx.remote.conf",
     "jumpstart_templates/i0n_rails_3/lib/development_mail_interceptor.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/authlogic.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/authlogic/session/session_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/authlogic/session/templates/session.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/datamapper.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/datamapper/migration/migration_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/datamapper/migration/templates/migration.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/datamapper/model/model_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/datamapper/model/templates/migration.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/datamapper/model/templates/model.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/datamapper/observer/observer_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/datamapper/observer/templates/observer.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/factory_girl.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/factory_girl/model/model_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/factory_girl/model/templates/fixtures.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_erb.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_erb/USAGE",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_erb/controller/controller_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_erb/controller/templates/view.html.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_erb/scaffold/scaffold_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_erb/scaffold/templates/_form.html.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_erb/scaffold/templates/edit.html.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_erb/scaffold/templates/index.html.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_erb/scaffold/templates/layout.html.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_erb/scaffold/templates/new.html.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_erb/scaffold/templates/show.html.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_haml.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_haml/USAGE",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_haml/controller/controller_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_haml/controller/templates/view.html.haml",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_haml/scaffold/scaffold_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_haml/scaffold/templates/_form.haml.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_haml/scaffold/templates/edit.haml.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_haml/scaffold/templates/index.haml.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_haml/scaffold/templates/layout.haml.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_haml/scaffold/templates/new.haml.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/formtastic_haml/scaffold/templates/show.haml.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/haml.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/haml/controller/controller_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/haml/controller/templates/view.html.haml",
     "jumpstart_templates/i0n_rails_3/lib/generators/haml/scaffold/scaffold_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/haml/scaffold/templates/_form.haml.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/haml/scaffold/templates/edit.haml.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/haml/scaffold/templates/index.haml.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/haml/scaffold/templates/layout.haml.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/haml/scaffold/templates/new.haml.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/haml/scaffold/templates/show.haml.erb",
     "jumpstart_templates/i0n_rails_3/lib/generators/machinist.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/machinist/model/model_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/machinist/model/templates/blueprint.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/machinist/model/templates/machinist_initializer.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/mongomapper.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/mongomapper/model/model_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/mongomapper/model/templates/model.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/mongomapper/observer/observer_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/shoulda.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/shoulda/controller/controller_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/shoulda/controller/templates/controller.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/shoulda/model/model_generator.rb",
     "jumpstart_templates/i0n_rails_3/lib/generators/shoulda/model/templates/model.rb",
     "jumpstart_templates/i0n_rails_3/lib/tasks/populate.rake",
     "jumpstart_templates/i0n_rails_3/public/javascripts/init.js",
     "jumpstart_templates/i0n_rails_3/public/javascripts/jquery-1.4.2.min.js",
     "jumpstart_templates/i0n_rails_3/public/javascripts/jquery-ui-1.8.custom.min.js",
     "jumpstart_templates/i0n_rails_3/public/javascripts/rails.js",
     "jumpstart_templates/i0n_rails_3/public/stylesheets/sass/_setup.sass",
     "jumpstart_templates/i0n_rails_3/public/stylesheets/sass/global.sass",
     "jumpstart_templates/i0n_rails_3/public/stylesheets/sass/handheld.sass",
     "jumpstart_templates/i0n_rails_3/public/stylesheets/sass/ie.sass",
     "jumpstart_templates/i0n_rails_3/public/stylesheets/sass/print.sass",
     "jumpstart_templates/i0n_rails_3/public/stylesheets/sass/screen.sass",
     "lib/jumpstart.rb",
     "lib/jumpstart/base.rb",
     "lib/jumpstart/doc/JumpStart.html",
     "lib/jumpstart/doc/JumpStart/Base.html",
     "lib/jumpstart/doc/base_rb.html",
     "lib/jumpstart/doc/created.rid",
     "lib/jumpstart/doc/index.html",
     "lib/jumpstart/doc/rdoc.css",
     "lib/jumpstart/filetools.rb",
     "source_templates/template_config.yml",
     "test/fake_nginx_path/local_nginx_1.conf",
     "test/fake_nginx_path/remote_nginx_1.conf",
     "test/helper.rb",
     "test/jumpstart/test_base.rb",
     "test/jumpstart/test_filetools.rb",
     "test/test_jumpstart.rb",
     "test/test_jumpstart_templates/test_base/_._test_file.txt",
     "test/test_jumpstart_templates/test_base/_._test_file_.txt",
     "test/test_jumpstart_templates/test_base/_1._test_file1.txt",
     "test/test_jumpstart_templates/test_base/_1._test_file1_.txt",
     "test/test_jumpstart_templates/test_base/_10._test_file2.txt",
     "test/test_jumpstart_templates/test_base/_99999._test_file3.txt",
     "test/test_jumpstart_templates/test_base/_a._test_file4.txt",
     "test/test_jumpstart_templates/test_base/test_file",
     "test/test_jumpstart_templates/test_base/test_file5.txt",
     "test/test_jumpstart_templates/test_base/test_file_.6txt",
     "test/test_jumpstart_templates/test_fileutils/append_after_line_test.txt",
     "test/test_jumpstart_templates/test_fileutils/append_to_end_of_file_source.txt",
     "test/test_jumpstart_templates/test_fileutils/append_to_end_of_file_test.txt",
     "test/test_jumpstart_templates/test_fileutils/check_source_type",
     "test/test_jumpstart_templates/test_fileutils/check_source_type.txt",
     "test/test_jumpstart_templates/test_fileutils/config_capistrano_source.rb",
     "test/test_jumpstart_templates/test_fileutils/config_capistrano_test.rb",
     "test/test_jumpstart_templates/test_fileutils/config_nginx_source.txt",
     "test/test_jumpstart_templates/test_fileutils/config_nginx_test.txt",
     "test/test_jumpstart_templates/test_fileutils/hosts_test",
     "test/test_jumpstart_templates/test_fileutils/insert_text_at_line_number_source.txt",
     "test/test_jumpstart_templates/test_fileutils/insert_text_at_line_number_test.txt",
     "test/test_jumpstart_templates/test_fileutils/remove_files_test_2.txt",
     "test/test_jumpstart_templates/test_fileutils/remove_files_test_3.txt",
     "test/test_jumpstart_templates/test_fileutils/remove_lines_test.txt",
     "test/test_jumpstart_templates/test_fileutils/replace_strings_test.rb",
     "test/test_jumpstart_templates/test_template_1/_._test_append_file_with_extension.txt",
     "test/test_jumpstart_templates/test_template_1/_._test_append_file_without_extension",
     "test/test_jumpstart_templates/test_template_1/_20._test_line_file_without_extension",
     "test/test_jumpstart_templates/test_template_1/_5._test_line_file_with_extension.txt",
     "test/test_jumpstart_templates/test_template_1/_L._test_append_to_end_of_file_remove_last_line_1.txt",
     "test/test_jumpstart_templates/test_template_1/_l._test_append_to_end_of_file_remove_last_line_2.txt",
     "test/test_jumpstart_templates/test_template_1/folder with spaces/_._test_append_file_with_extension.txt",
     "test/test_jumpstart_templates/test_template_1/folder with spaces/_._test_append_file_without_extension",
     "test/test_jumpstart_templates/test_template_1/folder with spaces/_5._test_line_file_with_extension.txt",
     "test/test_jumpstart_templates/test_template_1/folder with spaces/_50._test_line_file_without_extension",
     "test/test_jumpstart_templates/test_template_1/folder with spaces/test_whole_file_with_extension.txt",
     "test/test_jumpstart_templates/test_template_1/folder with spaces/test_whole_file_without_extension",
     "test/test_jumpstart_templates/test_template_1/jumpstart_config/test_template_1.yml",
     "test/test_jumpstart_templates/test_template_1/normal_folder_name/_._test_append_file_with_extension.txt",
     "test/test_jumpstart_templates/test_template_1/normal_folder_name/_._test_append_file_without_extension",
     "test/test_jumpstart_templates/test_template_1/normal_folder_name/_5._test_line_file_with_extension.txt",
     "test/test_jumpstart_templates/test_template_1/normal_folder_name/_50._test_line_file_without_extension",
     "test/test_jumpstart_templates/test_template_1/normal_folder_name/test_whole_file_with_extension.txt",
     "test/test_jumpstart_templates/test_template_1/normal_folder_name/test_whole_file_without_extension",
     "test/test_jumpstart_templates/test_template_1/test_append_to_end_of_file_remove_last_line_1.txt",
     "test/test_jumpstart_templates/test_template_1/test_append_to_end_of_file_remove_last_line_2.txt",
     "test/test_jumpstart_templates/test_template_1/test_remove_files/file_with_extension.txt",
     "test/test_jumpstart_templates/test_template_1/test_remove_files/file_without_extension",
     "test/test_jumpstart_templates/test_template_1/test_replace_strings/replace_strings_1.rb",
     "test/test_jumpstart_templates/test_template_1/test_replace_strings/replace_strings_2.txt",
     "test/test_jumpstart_templates/test_template_1/test_whole_file_with_extension.txt",
     "test/test_jumpstart_templates/test_template_1/test_whole_file_without_extension",
     "test/test_jumpstart_templates/test_template_2/jumpstart_config/test_template_2.yml",
     "test/test_jumpstart_templates/test_template_3/jumpstart_config/test_template_3.yml"
  ]
  s.homepage = %q{http://github.com/i0n/jumpstart}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Quickly start Ruby projects just the way you want them using a single YAML file and reusable templates.}
  s.test_files = [
    "test/helper.rb",
     "test/jumpstart/test_base.rb",
     "test/jumpstart/test_filetools.rb",
     "test/test_jumpstart.rb",
     "test/test_jumpstart_templates/test_fileutils/config_capistrano_source.rb",
     "test/test_jumpstart_templates/test_fileutils/config_capistrano_test.rb",
     "test/test_jumpstart_templates/test_fileutils/replace_strings_test.rb",
     "test/test_jumpstart_templates/test_template_1/test_replace_strings/replace_strings_1.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

